# Generated by Django 4.2 on 2024-09-19 03:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatRoomName',
            new_name='ChatRoomCommunity',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='community',
        ),
    ]
