# Generated by Django 4.2 on 2024-09-19 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_chatroomname_chatroomcommunity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='CommunityMessage',
        ),
        migrations.AlterModelOptions(
            name='chatroomcommunity',
            options={'verbose_name_plural': 'Chat Room Communities'},
        ),
    ]
