# Generated by Django 4.2 on 2024-09-19 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_usermessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='recipent',
            new_name='recipient',
        ),
    ]
