# Generated by Django 4.2 on 2024-09-19 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_chathistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='chat_community',
            new_name='community',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='chat_user',
        ),
        migrations.AddField(
            model_name='chathistory',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
