# Generated by Django 4.2 on 2024-09-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_chat_community_chathistory_community_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='community',
            new_name='communities',
        ),
    ]
