# Generated by Django 4.2 on 2024-09-20 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_rename_community_chathistory_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='communities',
            field=models.ManyToManyField(blank=True, to='chat.chatroomcommunity'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
