# Generated by Django 4.2 on 2024-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_recipient_usermessage_other_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='other_meessage_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
