# Generated by Django 4.2 on 2024-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_usermessage_other_meessage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
