# Generated by Django 4.2 on 2024-09-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_usermessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomcommunity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos'),
        ),
    ]
